language: objective-c
before_script:
  - cd src/OCJiraFeedback
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet  
  - pod install
script: 
  - xctool test -workspace OCJiraFeedback.xcworkspace/ -scheme OCJiraFeedback -sdk iphonesimulator
